import pandas as pd

configfile: "config/config.yaml"

# 1. read config/samples.tsv
samples_df = pd.read_csv("config/samples.tsv", sep="\t").set_index("sample_id", drop=False)

# 2. make sample_id list
SAMPLES = samples_df["sample_id"].tolist()

# 3. rull all
rule all:
    input:
        # Phase 1.1: renamed files
        expand("results/00_renamed/{s}_renamed.fasta", s=SAMPLES),
        # Phase 1.1: rename mapping files
        expand("results/00_renamed/{s}_mapping.tsv", s=SAMPLES),
        # Phase 1.2: results for BLAST DB
        expand("results/01_blastdb/{s}_renamed.nhr", s=SAMPLES),
        # Phase 2.1: blast sex markers and ID the renamed genomes
        expand("results/02_sex_id/{s}_sex_assignment.tsv", s=SAMPLES),
        # Phase 3: blast goflag probes and Tag "sex type" and extract All/Best Hits.
        expand("results/03_locus_search/{s}/A_all", s=SAMPLES),
        expand("results/03_locus_search/{s}/B_Best", s=SAMPLES),
        # Phase 4: select loci that are sex linked and qc
        "results/04_filtered/interesting_loci.txt",
        "results/04_filtered/collected_loci",
        # Phase 5: Align AA seqs (Order)
        "results/05_alignment/merged_with_ref"


include: "rules/preprocessing.smk"
include: "rules/sex_id.smk"
include: "rules/goflag_blast_locus_search.smk"
include: "rules/filtering_loci.smk"
include: "rules/alignment.smk"