import pandas as pd

configfile: "config/config.yaml"
RESULTS_DIR = config["paths"]["results"]
SAMPLES_DIR = config["paths"]["samples_tsv"]

# 1. read config/samples.tsv
samples_df = pd.read_csv(SAMPLES_DIR, sep="\t").set_index("sample_id", drop=False)

# 2. make sample_id list
raw_target = config.get("target_order")
TARGET_ORDER = str(raw_target).strip() if raw_target else "All"

if TARGET_ORDER.lower() != "all":   
    if "outgroup" not in config or not config["outgroup"]:
        raise ValueError(
            f"\n[ERROR] 'target_order'({TARGET_ORDER})\n"
        )
    
    OUTGROUP_ID = str(config["outgroup"]).strip()

    if OUTGROUP_ID not in samples_df["sample_id"].values:
        raise ValueError(f"\n[ERROR] The specified outgroup '{OUTGROUP_ID}' does not exist in the samples.tsv file!\n")

    target_list = [t.strip().lower() for t in TARGET_ORDER.split(",")]

    filtered_df = samples_df[(samples_df['order'].str.lower().isin(target_list)) | 
                             (samples_df['sample_id'] == OUTGROUP_ID)]
    
    SAMPLES = filtered_df["sample_id"].tolist()
    
    if len(SAMPLES) <= 1:
        raise ValueError(f"\n[ERROR] There are no samples for the target orders: {TARGET_ORDER}\n")

    print(f"\nTargeted Analysis Mode: {TARGET_ORDER} + Outgroup({OUTGROUP_ID})")
    print(f"Total samples selected: {len(SAMPLES)}\n")

else:   
    SAMPLES = samples_df["sample_id"].tolist()
    print(f"\nFull Analysis Mode: All {len(SAMPLES)} samples.\n")

# 3. Define dynamic targets for phylogeny and visualization
def get_dynamic_targets(wildcards):
    """
    Wait until checkpoint (Phase 4) is completed,
    read the generated all_sex_linked_genes.txt and return the final tree & viz file lists.
    """
    # 1. Get checkpoint output file (wait for Phase 4 completion)
    checkpoint_output = checkpoints.select_sex_linked_loci.get(**wildcards).output
    
    # 2. Read file and create gene ID list
    sex_linked_file = checkpoint_output.out_list
    autosomal_file =checkpoint_output.out_autosomal

    with open(sex_linked_file) as f:
        genes = [line.strip() for line in f if line.strip()]
    with open(autosomal_file) as f:
        autosomal_genes = [line.strip() for line in f if line.strip()]
        
    # 3. Return Trimmed Alignment file paths (Trees)
    trees_sex_linked = expand(f"{RESULTS_DIR}/07_phylogeny/{{type}}/{{gene}}.treefile", 
                   type=["Best", "All"], 
                   gene=genes)
    trees_autosomal = expand(f"{RESULTS_DIR}/07_phylogeny/autosomal/{{gene}}.treefile",
                                  gene=autosomal_genes)

    # Combine and return both target lists
    return trees_sex_linked + trees_autosomal

# 4. Rule all
rule all:
    input:
        # Phase 1.1: renamed files
        expand(f"{RESULTS_DIR}/00_renamed/{{s}}_renamed.fasta", s=SAMPLES),
        # Phase 1.1: rename mapping files
        expand(f"{RESULTS_DIR}/00_renamed/{{s}}_mapping.tsv", s=SAMPLES),
        # Phase 1.2: results for BLAST DB
        expand(f"{RESULTS_DIR}/01_blastdb/{{s}}_renamed.nhr", s=SAMPLES),
        # Phase 2.1: blast sex markers and ID the renamed genomes
        expand(f"{RESULTS_DIR}/02_sex_id/{{s}}_sex_assignment.tsv", s=SAMPLES),
        f"{RESULTS_DIR}/02_sex_id/all_samples_sex_assignment.tsv",
        # Phase 3: blast goflag probes and Tag "sex type" and extract All/Best Hits.
        expand(f"{RESULTS_DIR}/03_locus_search/{{s}}/A_All_hits.tsv", s=SAMPLES),
        expand(f"{RESULTS_DIR}/03_locus_search/{{s}}/B_Best_hits.tsv", s=SAMPLES),
        # Phase 4: select loci that are sex linked and qc
        f"{RESULTS_DIR}/04_filtered/all_sex_linked_genes.txt",
        f"{RESULTS_DIR}/04_filtered/sex_linked_species_lists.tsv",
        f"{RESULTS_DIR}/04_filtered/sex_linked_summary_by_order.tsv",
        f"{RESULTS_DIR}/04_filtered/autosomal_genes.txt",
        expand(f"{RESULTS_DIR}/04_filtered/dup_tagged_og/{{s}}_classified.tsv", s=SAMPLES),
        f"{RESULTS_DIR}/04_filtered/all_samples_classified_duplications.tsv",
        # Phase 5: Extract sequences
        expand(f"{RESULTS_DIR}/05_extracted/{{s}}/Best", s=SAMPLES),
        expand(f"{RESULTS_DIR}/05_extracted/{{s}}/All", s=SAMPLES),
        expand(f"{RESULTS_DIR}/05_extracted/{{s}}/autosomal", s=SAMPLES),
        # Phase 6 & 7: MSA, TrimAL, IQTree, and Viz (dynamic targets)
        get_dynamic_targets


include: "rules/01_preprocess.smk"
include: "rules/02_assign_sex.smk"
include: "rules/03_blast_goflag_probes.smk"
include: "rules/04_filter_sex_linked.smk"
include: "rules/05_extract_seqs.smk"
include: "rules/06_align_trim.smk"
include: "rules/07_phylogeny.smk"