# ---------------------------------------------------------
# UVfinder Pipeline Configuration
# ---------------------------------------------------------

# parameters settings
params:
  uv_blast_evalue: 1e-11 # E-value for UV marker BLAST searches
  query_blast_evalue: 1e-10  # E-value for Goflag query BLAST searches
  min_coverage: 0.3         # amino acid sequence coverage minimum threshold (%)
  min_identity: 30          # amino acid sequence identity minimum threshold (%)
  flanking_bp: 2000         # BLAST hit flanking sequence length (bp)

# file paths
paths:
  samples_tsv: "config/samples.tsv"
  genomes: "resources/genomes"
  female_markers: "resources/sex_markers/female_sex_markers.fasta"
  male_markers: "resources/sex_markers/male_sex_markers.fasta"
  query_sets: "resources/query_sets"
  ref_alignments: "resources/ref_aligns"
  results: "results"

# QC filtering options
qc:
  remove_stop_codons: true  # options for internal stop codon
  check_frameshift: true    # options for frameshift mutations

# analysis tool additional options
tools:
  trimal: "-automated1"     # trimAl automatic mode
  iqtree:
    model: "MFP"            # optimal model test and tree generation (ModelFinder Plus)
    bootstrap: 1000         # Ultrafast Bootstrap iterations